/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.util.ArrayList;

/**
 *
 * @author GONZALO
 */
public class MenuPrincipal extends javax.swing.JFrame {

    //public static ArrayList<ListaDeUsuario> = new ArrayList();
    /**
     * Creates new form JFrmMenuPrincipal
     */
    public MenuPrincipal() {
        
        initComponents();
        
       this.setLocationRelativeTo(null);
       this.setTitle("MENU PRINCIPAL");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        LblBienvenida = new javax.swing.JLabel();
        Barrademenu = new javax.swing.JMenuBar();
        MenuInicio = new javax.swing.JMenu();
        ItemIngresar = new javax.swing.JMenuItem();
        MenuRoles = new javax.swing.JMenu();
        ItemCrearRoles = new javax.swing.JMenuItem();
        ItemModificar = new javax.swing.JMenuItem();
        ItemEliminarrol = new javax.swing.JMenuItem();
        MenuUsuario = new javax.swing.JMenu();
        CerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MenuPrincipal");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel1.setBackground(new java.awt.Color(255, 153, 51));
        Panel1.setName("Panel1"); // NOI18N

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        getContentPane().add(Panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 430));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        LblBienvenida.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LblBienvenida.setText("BIENVENIDO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(LblBienvenida)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(LblBienvenida)
                .addContainerGap(310, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 0, 190, 430));

        MenuInicio.setText("Inicio");
        MenuInicio.setName("MenuInicio"); // NOI18N

        ItemIngresar.setText("Ingresar a Sitema");
        ItemIngresar.setName("ItemIngresar"); // NOI18N
        ItemIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemIngresarActionPerformed(evt);
            }
        });
        MenuInicio.add(ItemIngresar);

        Barrademenu.add(MenuInicio);

        MenuRoles.setText("Roles");
        MenuRoles.setName("MenuRoles"); // NOI18N

        ItemCrearRoles.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        ItemCrearRoles.setText("Crear Roles");
        ItemCrearRoles.setName("ItemCrearRoles"); // NOI18N
        ItemCrearRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemCrearRolesActionPerformed(evt);
            }
        });
        MenuRoles.add(ItemCrearRoles);

        ItemModificar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        ItemModificar.setText("Modificar rol");
        ItemModificar.setName("ItemModificar"); // NOI18N
        MenuRoles.add(ItemModificar);

        ItemEliminarrol.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        ItemEliminarrol.setText("Eliminar rol");
        ItemEliminarrol.setName("ItemEliminarrol"); // NOI18N
        MenuRoles.add(ItemEliminarrol);

        Barrademenu.add(MenuRoles);

        MenuUsuario.setText("Usuario");
        MenuUsuario.setName("MenuUsuario"); // NOI18N

        CerrarSesion.setText("Cerrar Sesion");
        CerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarSesionActionPerformed(evt);
            }
        });
        MenuUsuario.add(CerrarSesion);

        Barrademenu.add(MenuUsuario);

        setJMenuBar(Barrademenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ItemCrearRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemCrearRolesActionPerformed
    }//GEN-LAST:event_ItemCrearRolesActionPerformed

    private void CerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarSesionActionPerformed
    }//GEN-LAST:event_CerrarSesionActionPerformed

    private void ItemIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemIngresarActionPerformed
    }//GEN-LAST:event_ItemIngresarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Barrademenu;
    public javax.swing.JMenuItem CerrarSesion;
    public javax.swing.JMenuItem ItemCrearRoles;
    public javax.swing.JMenuItem ItemEliminarrol;
    public javax.swing.JMenuItem ItemIngresar;
    public javax.swing.JMenuItem ItemModificar;
    private javax.swing.JLabel LblBienvenida;
    private javax.swing.JMenu MenuInicio;
    private javax.swing.JMenu MenuRoles;
    private javax.swing.JMenu MenuUsuario;
    private javax.swing.JPanel Panel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
